### ISSUE TITLE
Name attribute is used to determine the username from user info response

### ISSUE THREAD

**Issue by sevasm** [kmeadows1980/jasperserver#5]
When user details are parsed in OAuthUserDetailsServiceImpl.java, the "name" attribute is used to determine the username of the user logging in. According to the OpenID Connect specification (https://openid.net/specs/openid-connect-basic-1_0.html) the "name" attribute refers to the "End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences.". Therefore it does not represent an actual username and is subject to changing over time.

The OpenID Connect specification also defines the "preferred_username" attribute as "Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe.". Could this be a more appropriate attribute to use as the username instead of "name"?

**Comment by kmeadows1980** [comment]
You are free to modify the userdetailsservice implementation as you see fit and re-compile.
This is a base example but custom providers can return whatever json they want so it is feasible to parse out the userdetail information as well as any profile attributes for JRS security as you see fit.

Thanks.

**Comment by sevasm** [comment]
Thanks for the reply! We would very much prefer not to create our own fork. Would you consider a pull request that would allow at least the attribute used to parse the username from the user details to be configurable, leaving "name" as the default value if it's not explicitly configured to be something else?
